'use client';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell, LineChart, Line, Area, AreaChart } from 'recharts';

export function Charts({ monthlyData, categoryData, goalProgress }: any) {
  return <div className='grid grid-cols-1 gap-4 lg:grid-cols-2'>
    <div className='rounded-xl border border-neutral-800 bg-neutral-900 p-4 lg:col-span-2'><h3 className='mb-3 text-lg font-semibold'>Monthly Overview</h3><ResponsiveContainer width='100%' height={300}><BarChart data={monthlyData}><CartesianGrid strokeDasharray='3 3' /><XAxis dataKey='month' /><YAxis /><Tooltip /><Legend /><Bar dataKey='income' fill='#22c55e' /><Bar dataKey='expenses' fill='#ef4444' /><Bar dataKey='savings' fill='#3b82f6' /></BarChart></ResponsiveContainer></div>
    <div className='rounded-xl border border-neutral-800 bg-neutral-900 p-4'><h3 className='mb-3 text-lg font-semibold'>Expense Categories</h3><ResponsiveContainer width='100%' height={280}><PieChart><Pie data={categoryData} dataKey='value' cx='50%' cy='50%' outerRadius={90}>{categoryData.map((e:any,i:number)=><Cell key={i} fill={e.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div>
    <div className='rounded-xl border border-neutral-800 bg-neutral-900 p-4'><h3 className='mb-3 text-lg font-semibold'>Goal Progress</h3><ResponsiveContainer width='100%' height={280}><BarChart data={goalProgress}><CartesianGrid strokeDasharray='3 3' /><XAxis dataKey='name' /><YAxis /><Tooltip /><Bar dataKey='current' fill='#22c55e' /><Bar dataKey='target' fill='#64748b' /></BarChart></ResponsiveContainer></div>
    <div className='rounded-xl border border-neutral-800 bg-neutral-900 p-4 lg:col-span-2'><h3 className='mb-3 text-lg font-semibold'>Savings Trend</h3><ResponsiveContainer width='100%' height={260}><AreaChart data={monthlyData}><CartesianGrid strokeDasharray='3 3' /><XAxis dataKey='month' /><YAxis /><Tooltip /><Area type='monotone' dataKey='savings' stroke='#3b82f6' fill='#3b82f6' fillOpacity={0.5} /></AreaChart></ResponsiveContainer></div>
    <div className='rounded-xl border border-neutral-800 bg-neutral-900 p-4 lg:col-span-2'><h3 className='mb-3 text-lg font-semibold'>Cash Flow Analysis</h3><ResponsiveContainer width='100%' height={280}><LineChart data={monthlyData}><CartesianGrid strokeDasharray='3 3' /><XAxis dataKey='month' /><YAxis /><Tooltip /><Legend /><Line type='monotone' dataKey='income' stroke='#22c55e' /><Line type='monotone' dataKey='expenses' stroke='#ef4444' /><Line type='monotone' dataKey='savings' stroke='#3b82f6' /></LineChart></ResponsiveContainer></div>
  </div>;
}

