'use client';
import { useEffect, useState } from 'react';
import { LoanFormData, Account } from '@/lib/types';
import { useAuthContext } from '@/components/AuthProvider';
import { useAuthedQuery } from '@/hooks/useAuthedQuery';

export function LoanForm({ open, onClose, onSubmit, accounts, editingLoan }: {open:boolean;onClose:()=>void;onSubmit:(d:LoanFormData)=>Promise<void>;accounts:Account[];editingLoan?:any;}) {
  const { user } = useAuthContext();
  const { data: people = [] } = useAuthedQuery(user, ['people', user?.uid], '/api/people');
  const [form, setForm] = useState<any>({ loanType: 'lent', personId: '', principalAmount: '', startDate: '', dueDate: '', note: '', fromAccountId: '', toAccountId: '' });
  useEffect(()=>{setForm({loanType:editingLoan?.loanType||'lent',personId:editingLoan?.personId||'',principalAmount:editingLoan?.principalAmount||'',startDate:editingLoan?.startDate?new Date(editingLoan.startDate).toISOString().slice(0,10):new Date().toISOString().slice(0,10),dueDate:editingLoan?.dueDate?new Date(editingLoan.dueDate).toISOString().slice(0,10):'',note:editingLoan?.note||'',fromAccountId:editingLoan?.fromAccountId||'',toAccountId:editingLoan?.toAccountId||''});},[editingLoan,open]);
  if(!open) return null;
  return <div className='fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4'><form className='w-full max-w-lg space-y-3 rounded-xl bg-neutral-900 p-4' onSubmit={async e=>{e.preventDefault(); const person=(people as any[]).find((p:any)=>p.id===form.personId); await onSubmit({...form,principalAmount:Number(form.principalAmount),startDate:new Date(form.startDate),dueDate:form.dueDate?new Date(form.dueDate):undefined,personName:person?.name||''} as any); onClose();}}><h3 className='text-lg font-semibold'>{editingLoan?'Edit':'Add'} Loan</h3><select className='w-full rounded bg-neutral-800 p-2' value={form.loanType} onChange={e=>setForm({...form,loanType:e.target.value})}><option value='lent'>Lent</option><option value='borrowed'>Borrowed</option><option value='payable'>Payable</option></select><select className='w-full rounded bg-neutral-800 p-2' value={form.personId} onChange={e=>setForm({...form,personId:e.target.value})}><option value=''>Select person</option>{(people as any[]).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className='w-full rounded bg-neutral-800 p-2' type='number' placeholder='Amount' value={form.principalAmount} onChange={e=>setForm({...form,principalAmount:e.target.value})}/><input className='w-full rounded bg-neutral-800 p-2' type='date' value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/><input className='w-full rounded bg-neutral-800 p-2' type='date' value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/><textarea className='w-full rounded bg-neutral-800 p-2' placeholder='Note' value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><div className='flex justify-end gap-2'><button type='button' className='rounded border px-3 py-2' onClick={onClose}>Cancel</button><button className='rounded bg-emerald-600 px-3 py-2'>Save</button></div></form></div>;
}
